### PR TITLE
Jing's Mac seemed to need the absolute siad path

### PR DESCRIPTION
**Pull request by Mingling94**

### CODE REVIEW

**Comment by Mingling94** [comment]
@lukechampine @DavidVorick This should be merged (if the naming is okay). Then to include it with the UI's release:
- version bump the repo via `npm version minor` or `npm version patch`
- publish to [npm registry](https://www.npmjs.com/package/sia.js) via `npm publish`
- bump Sia-UI's sia.js version with `npm install -S sia.js`

**Comment by lukechampine** [comment]
Do we need to set up permissions in order to publish to npm ourselves?

**Comment by Mingling94** [comment]
Good point, make npm accounts and I'll add you as contributors on npmjs.com

**Comment by lukechampine** [comment]
Aight, here I am: https://www.npmjs.com/~lukechampine

**Comment by DavidVorick** [comment]
https://www.npmjs.com/~taek

**Comment by Mingling94** [comment]
Done

**Pull request merged**
