### PR TITLE
Set object passed into configure() have siad properties

### PR DESCRIPTION
**Pull request by Mingling94**
This way, a settings plugin in the UI could see these members and mess with them.

Cuz we expose the siad object's members.

Exposing our members can't hurt, right? :wink:

### CODE REVIEW

**Comment by DavidVorick** [comment]
I'm not sure I understand why this is useful? Isn't there not a way to list all the settings?

I don't see what the use case is

**Comment by Mingling94** [comment]
There is not a way to list all the settings, `siad` the object with properties is private to the wrapper.

The use case is for if one wants to get an object in their own code with all the settings, such as with a settings plugin.

**Comment by DavidVorick** [comment]
Are there going to be problems if someone tries to modify a settings field without going through the `configure` function, or doing things like adding fields? Want to make sure we preserve type-safety.

**Comment by Mingling94** [comment]
Nah this would pass by copy, to affect changes to ports or other options, one would have to re`configure`.

It could however, return the settings object itself which is pass by reference? Is that desirable?

**Comment by DavidVorick** [comment]
No, we should keep it so that you need to call `configure` to change any settings

**Comment by DavidVorick** [comment]
needs rebase

**Comment by Mingling94** [comment]
boop @lukechampine @DavidVorick

**Pull request merged**
